<script lang="ts">
	import { onMount } from 'svelte';
    	import { create, all } from 'mathjs';

        	// Initialize mathjs for complex number evaluation
            	const math = create(all);

                	let { 
                        		initialFunction = '1 / (z - 1)',
                                		resolution = 250 // Low res for performance, scaled up via CSS
                    } = $props();

                    	let canvas = $state<HTMLCanvasElement>();
                        	let expression = $state(initialFunction);
                            	let error = $state<string | null>(null);
                                	let isProcessing = $state(false);

                                    	// Derived dimensions
                                        	let width = $derived(resolution);
                                            	let height = $derived(resolution);

                                                	// The "camera" window in the complex plane
                                                    	const range = 3; // Real and Imaginary axis from -3 to +3

                                                        	// HSL to RGB helper for domain coloring
                                                            	function HSLToRGB(h: number, s: number, l: number) {
                                                                    		s /= 100;
                                                                            		l /= 100;
                                                                                    		const k = (n: number) => (n + h / 30) % 12;
                                                                                            		const a = s * Math.min(l, 1 - l);
                                                                                                    		const f = (n: number) =>
                                                                                                            			l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
                                                                                                                        		return [255 * f(0), 255 * f(8), 255 * f(4)];
                                                                }

                                                                	// Reactive effect: Redraw whenever expression changes
                                                                    	$effect(() => {
                                                                            		if (canvas && expression) {
                                                                                        			draw(expression);
                                                                                    }
                                                                        });

                                                                        	async function draw(expr: string) {
                                                                                		if (!canvas) return;
                                                                                        		isProcessing = true;
                                                                                                		error = null;

                                                                                                        		// Small timeout to let UI show the spinner before blocking the thread
                                                                                                                		setTimeout(() => {
                                                                                                                            			try {
                                                                                                                                            				const ctx = canvas!.getContext('2d');
                                                                                                                                                            				if (!ctx) return;

                                                                                                                                                                            				const compiled = math.compile(expr);
                                                                                                                                                                                            				const imgData = ctx.createImageData(width, height);
                                                                                                                                                                                                            				const data = imgData.data;

                                                                                                                                                                                                                            				// Iterate over every pixel
                                                                                                                                                                                                                                            				for (let x = 0; x < width; x++) {
                                                                                                                                                                                                                                                                					for (let y = 0; y < height; y++) {
                                                                                                                                                                                                                                                                                        						// Normalize x,y to complex plane coordinates [-range, range]
                                                                                                                                                                                                                                                                                                                						const re = ((x / width) * 2 - 1) * range;
                                                                                                                                                                                                                                                                                                                                        						const im = -((y / height) * 2 - 1) * range; // Invert Y for standard cartesian

                                                                                                                                                                                                                                                                                                                                                                						let val;
                                                                                                                                                                                                                                                                                                                                                                                        						try {
                                                                                                                                                                                                                                                                                                                                                                                                                    							// Evaluate f(z)
                                                                                                                                                                                                                                                                                                                                                                                                                                                							val = compiled.evaluate({ z: math.complex(re, im) });
                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                    							val = math.complex(0, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                						// Handle real number results (convert to complex)
                                                                                                                                                                                                                                                                                                                                                                                                                                        						if (typeof val === 'number') val = math.complex(val, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                						// --- Domain Coloring Logic ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						// Hue = Argument (Angle)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						// Lightness = Modulus (Magnitude)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						const r = val.toPolar().r;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						const phi = val.toPolar().phi; // -PI to +PI

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						// Hue: Map angle to 0-360
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						let hue = (phi * 180) / Math.PI;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						if (hue < 0) hue += 360;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						// Brightness/Contours: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						// Use log scale for magnitude to handle poles/zeros gracefully
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						// The sine wave creates the "contour lines" effect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						const magnitudeLog = Math.log(r + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						const lightness = 50 + 20 * Math.sin(10 * magnitudeLog);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						const [red, green, blue] = HSLToRGB(hue, 100, lightness);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						// Pixel index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						const index = (x + y * width) * 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						data[index] = red;     // R
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						data[index + 1] = green; // G
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						data[index + 2] = blue;  // B
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                						data[index + 3] = 255;   // Alpha
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                            				ctx.putImageData(imgData, 0, 0);
                                                                                                                                        } catch (err: any) {
                                                                                                                                            				error = err.message || "Invalid function";
                                                                                                                                        } finally {
                                                                                                                                            				isProcessing = false;
                                                                                                                                        }
                                                                                                                        }, 10);
                                                                            }
                                                                            </script>

                                                                            <div class="card my-8 border-l-4 border-l-gold bg-white dark:bg-neutral-800 p-6 shadow-xl">
                                                                            	<div class="mb-4 flex flex-col gap-4 sm:flex-row sm:items-end">
                                                                                		<div class="w-full">
                                                                                        			<label 
                                                                                                    				for="complex-input" 
                                                                                                                    				class="mb-1 block text-sm font-bold text-neutral-600 dark:text-neutral-400"
                                                                                                                                    			>
                                                                                                                                                				f(z) =
                                                                                                                                                                			</label>
                                                                                                                                                                            			<div class="relative">
                                                                                                                                                                                        				<input
                                                                                                                                                                                                        					id="complex-input"
                                                                                                                                                                                                                            					type="text"
                                                                                                                                                                                                                                                					bind:value={expression}
                                                                                                                                                                                                                                                                    					class="w-full rounded-md border border-neutral-300 bg-neutral-50 px-3 py-2 font-mono text-neutral-900 focus:border-gold focus:ring-1 focus:ring-gold dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-100"
                                                                                                                                                                                                                                                                                        					placeholder="e.g. 1 / (z - 1)"
                                                                                                                                                                                                                                                                                                            				/>
                                                                                                                                                                                                                                                                                                                            				{#if isProcessing}
                                                                                                                                                                                                                                                                                                                                            					<div class="absolute right-3 top-2.5">
                                                                                                                                                                                                                                                                                                                                                                						<div class="h-4 w-4 animate-spin rounded-full border-2 border-gold border-t-transparent"></div>
                                                                                                                                                                                                                                                                                                                                                                                        					</div>
                                                                                                                                                                                                                                                                                                                                                                                                            				{/if}
                                                                                                                                                                                                                                                                                                                                                                                                                            			</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        			{#if error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    				<p class="mt-1 animate-pulse font-mono text-xs text-red-500">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			{/if}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		<div class="flex gap-2 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			<button class="btn-preset" onclick={() => expression = 'z^2 + 1'}>z²+1</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			<button class="btn-preset" onclick={() => expression = '1/z'}>1/z</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			<button class="btn-preset" onclick={() => expression = 'sin(z)'}>sin(z)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	<div class="relative aspect-square w-full overflow-hidden rounded-lg border-2 border-neutral-200 shadow-inner dark:border-neutral-700 md:aspect-video">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		<canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			bind:this={canvas}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			{width}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			{height}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			class="h-full w-full object-contain [image-rendering:pixelated]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		></canvas>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		<div class="pointer-events-none absolute bottom-2 right-2 rounded bg-black/70 px-2 py-1 font-mono text-[10px] text-white backdrop-blur-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			Re: [-{range}, {range}] Im: [-{range}, {range}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	.btn-preset {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		@apply rounded bg-neutral-200 px-2 py-2 font-mono text-neutral-700 hover:bg-gold hover:text-white dark:bg-neutral-700 dark:text-neutral-300 dark:hover:bg-gold cursor-pointer transition-colors;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                        }
                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                            }
                                                                                                                                        }
                                                                                                                        })
                                                                            }
                                                                                    }
                                                                        })
                                                                }
                    }